# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Connection do
  @moduledoc """
  Handle Tesla connections for RecipesBot.SpoonacularClient.
  """

  use Tesla

  # Add any middleware here (authentication)
  plug Tesla.Middleware.BaseUrl,
       Application.get_env(:recipes_bot, :spoonacular_base_url, "https://api.spoonacular.com")

  plug Tesla.Middleware.Headers, [{"user-agent", "Elixir"}]
  plug Tesla.Middleware.EncodeJson, engine: Poison

  plug Tesla.Middleware.Query,
    apiKey: Application.get_env(:recipes_bot, :spoonacular_api_key, "Your API key here")

  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  @spec new() :: Tesla.Env.client()
  def new do
    Tesla.client([])
  end
end
