# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.AddMealPlanTemplate200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :items,
    :publishAsPublic
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :items => [
            RecipesBot.SpoonacularClient.Model.AddMealPlanTemplate200ResponseItemsInner.t()
          ],
          :publishAsPublic => boolean()
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.AddMealPlanTemplate200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :items,
      :list,
      RecipesBot.SpoonacularClient.Model.AddMealPlanTemplate200ResponseItemsInner,
      options
    )
  end
end
