# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.AddToMealPlanRequest1 do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :date,
    :slot,
    :position,
    :type,
    :value
  ]

  @type t :: %__MODULE__{
          :date => float(),
          :slot => integer(),
          :position => integer(),
          :type => String.t(),
          :value => RecipesBot.SpoonacularClient.Model.AddToMealPlanRequest1Value.t()
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.AddToMealPlanRequest1 do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :value,
      :struct,
      RecipesBot.SpoonacularClient.Model.AddToMealPlanRequest1Value,
      options
    )
  end
end
