# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.AddToMealPlanRequest1Value do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ingredients
  ]

  @type t :: %__MODULE__{
          :ingredients => [
            RecipesBot.SpoonacularClient.Model.AddToMealPlanRequest1ValueIngredientsInner.t()
          ]
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.AddToMealPlanRequest1Value do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :ingredients,
      :list,
      RecipesBot.SpoonacularClient.Model.AddToMealPlanRequest1ValueIngredientsInner,
      options
    )
  end
end
