# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.AddMealPlanTemplate200ResponseItemsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :day,
    :slot,
    :position,
    :type,
    :value
  ]

  @type t :: %__MODULE__{
          :day => integer(),
          :slot => integer(),
          :position => integer(),
          :type => String.t(),
          :value =>
            RecipesBot.SpoonacularClient.Model.AddMealPlanTemplate200ResponseItemsInnerValue.t()
            | nil
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.AddMealPlanTemplate200ResponseItemsInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :value,
      :struct,
      RecipesBot.SpoonacularClient.Model.AddMealPlanTemplate200ResponseItemsInnerValue,
      options
    )
  end
end
