# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :steps
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :steps =>
            [
              RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInner.t()
            ]
            | nil
        }
end

defimpl Poison.Decoder,
  for:
    RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :steps,
      :list,
      RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInner,
      options
    )
  end
end
