# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :step,
    :ingredients,
    :equipment
  ]

  @type t :: %__MODULE__{
          :number => float(),
          :step => String.t(),
          :ingredients =>
            [
              RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner.t()
            ]
            | nil,
          :equipment =>
            [
              RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner.t()
            ]
            | nil
        }
end

defimpl Poison.Decoder,
  for:
    RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :ingredients,
      :list,
      RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner,
      options
    )
    |> deserialize(
      :equipment,
      :list,
      RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner,
      options
    )
  end
end
