# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :localizedName,
    :image
  ]

  @type t :: %__MODULE__{
          :id => float(),
          :name => String.t(),
          :localizedName => String.t(),
          :image => String.t()
        }
end

defimpl Poison.Decoder,
  for:
    RecipesBot.SpoonacularClient.Model.AnalyzeRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner do
  def decode(value, _options) do
    value
  end
end
