# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.AutocompleteMenuItemSearch200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :results
  ]

  @type t :: %__MODULE__{
          :results => [
            RecipesBot.SpoonacularClient.Model.AutocompleteProductSearch200ResponseResultsInner.t()
          ]
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.AutocompleteMenuItemSearch200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :results,
      :list,
      RecipesBot.SpoonacularClient.Model.AutocompleteProductSearch200ResponseResultsInner,
      options
    )
  end
end
