# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.ClassifyGroceryProductBulk200ResponseInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :cleanTitle,
    :image,
    :category,
    :breadcrumbs,
    :usdaCode
  ]

  @type t :: %__MODULE__{
          :cleanTitle => String.t(),
          :image => String.t(),
          :category => String.t(),
          :breadcrumbs => [String.t()],
          :usdaCode => integer()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.ClassifyGroceryProductBulk200ResponseInner do
  def decode(value, _options) do
    value
  end
end
