# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.DetectFoodInText200ResponseAnnotationsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :annotation,
    :image,
    :tag
  ]

  @type t :: %__MODULE__{
          :annotation => String.t(),
          :image => String.t(),
          :tag => String.t()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.DetectFoodInText200ResponseAnnotationsInner do
  def decode(value, _options) do
    value
  end
end
