# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.DetectFoodInText200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :annotations
  ]

  @type t :: %__MODULE__{
          :annotations => [
            RecipesBot.SpoonacularClient.Model.DetectFoodInText200ResponseAnnotationsInner.t()
          ]
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.DetectFoodInText200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :annotations,
      :list,
      RecipesBot.SpoonacularClient.Model.DetectFoodInText200ResponseAnnotationsInner,
      options
    )
  end
end
