# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetConversationSuggests200ResponseSuggests do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :_
  ]

  @type t :: %__MODULE__{
          :_ => [
            RecipesBot.SpoonacularClient.Model.GetConversationSuggests200ResponseSuggestsInner.t()
          ]
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetConversationSuggests200ResponseSuggests do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :_,
      :list,
      RecipesBot.SpoonacularClient.Model.GetConversationSuggests200ResponseSuggestsInner,
      options
    )
  end
end
