# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetRecipeNutritionWidgetById200ResponseGoodInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :indented,
    :percentOfDailyNeeds,
    :name
  ]

  @type t :: %__MODULE__{
          :amount => String.t(),
          :indented => boolean(),
          :percentOfDailyNeeds => float(),
          :name => String.t()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetRecipeNutritionWidgetById200ResponseGoodInner do
  def decode(value, _options) do
    value
  end
end
