# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInnerItemsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :slot,
    :position,
    :type,
    :value
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :slot => integer(),
          :position => integer(),
          :type => String.t(),
          :value =>
            RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInnerItemsInnerValue.t()
            | nil
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInnerItemsInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :value,
      :struct,
      RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInnerItemsInnerValue,
      options
    )
  end
end
