# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetWinePairing200ResponseProductMatchesInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :averageRating,
    :description,
    :imageUrl,
    :link,
    :price,
    :ratingCount,
    :score
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :title => String.t(),
          :averageRating => float(),
          :description => AnyType | nil,
          :imageUrl => String.t(),
          :link => String.t(),
          :price => String.t(),
          :ratingCount => integer(),
          :score => float()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetWinePairing200ResponseProductMatchesInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:description, :struct, RecipesBot.SpoonacularClient.Model.AnyType, options)
  end
end
