# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetWineRecommendation200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :recommendedWines,
    :totalFound
  ]

  @type t :: %__MODULE__{
          :recommendedWines => [
            RecipesBot.SpoonacularClient.Model.GetWineRecommendation200ResponseRecommendedWinesInner.t()
          ],
          :totalFound => integer()
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.GetWineRecommendation200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :recommendedWines,
      :list,
      RecipesBot.SpoonacularClient.Model.GetWineRecommendation200ResponseRecommendedWinesInner,
      options
    )
  end
end
