# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetWinePairing200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :pairedWines,
    :pairingText,
    :productMatches
  ]

  @type t :: %__MODULE__{
          :pairedWines => [String.t()],
          :pairingText => String.t(),
          :productMatches => [
            RecipesBot.SpoonacularClient.Model.GetWinePairing200ResponseProductMatchesInner.t()
          ]
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.GetWinePairing200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :productMatches,
      :list,
      RecipesBot.SpoonacularClient.Model.GetWinePairing200ResponseProductMatchesInner,
      options
    )
  end
end
