# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetRecipeNutritionWidgetById200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :calories,
    :carbs,
    :fat,
    :protein,
    :bad,
    :good
  ]

  @type t :: %__MODULE__{
          :calories => String.t(),
          :carbs => String.t(),
          :fat => String.t(),
          :protein => String.t(),
          :bad => [
            RecipesBot.SpoonacularClient.Model.GetRecipeNutritionWidgetById200ResponseBadInner.t()
          ],
          :good => [
            RecipesBot.SpoonacularClient.Model.GetRecipeNutritionWidgetById200ResponseGoodInner.t()
          ]
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetRecipeNutritionWidgetById200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :bad,
      :list,
      RecipesBot.SpoonacularClient.Model.GetRecipeNutritionWidgetById200ResponseBadInner,
      options
    )
    |> deserialize(
      :good,
      :list,
      RecipesBot.SpoonacularClient.Model.GetRecipeNutritionWidgetById200ResponseGoodInner,
      options
    )
  end
end
