# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetShoppingList200ResponseAislesInnerItemsInnerMeasures do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :original,
    :metric,
    :us
  ]

  @type t :: %__MODULE__{
          :original =>
            RecipesBot.SpoonacularClient.Model.ParseIngredients200ResponseInnerNutritionWeightPerServing.t(),
          :metric =>
            RecipesBot.SpoonacularClient.Model.ParseIngredients200ResponseInnerNutritionWeightPerServing.t(),
          :us =>
            RecipesBot.SpoonacularClient.Model.ParseIngredients200ResponseInnerNutritionWeightPerServing.t()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetShoppingList200ResponseAislesInnerItemsInnerMeasures do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :original,
      :struct,
      RecipesBot.SpoonacularClient.Model.ParseIngredients200ResponseInnerNutritionWeightPerServing,
      options
    )
    |> deserialize(
      :metric,
      :struct,
      RecipesBot.SpoonacularClient.Model.ParseIngredients200ResponseInnerNutritionWeightPerServing,
      options
    )
    |> deserialize(
      :us,
      :struct,
      RecipesBot.SpoonacularClient.Model.ParseIngredients200ResponseInnerNutritionWeightPerServing,
      options
    )
  end
end
