# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetShoppingList200ResponseAislesInnerItemsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :measures,
    :pantryItem,
    :aisle,
    :cost,
    :ingredientId
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :name => String.t(),
          :measures =>
            RecipesBot.SpoonacularClient.Model.GetShoppingList200ResponseAislesInnerItemsInnerMeasures.t()
            | nil,
          :pantryItem => boolean(),
          :aisle => String.t(),
          :cost => float(),
          :ingredientId => integer()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetShoppingList200ResponseAislesInnerItemsInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :measures,
      :struct,
      RecipesBot.SpoonacularClient.Model.GetShoppingList200ResponseAislesInnerItemsInnerMeasures,
      options
    )
  end
end
