# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetProductInformation200ResponseIngredientsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :name,
    :safety_level
  ]

  @type t :: %__MODULE__{
          :description => AnyType | nil,
          :name => String.t(),
          :safety_level => AnyType | nil
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetProductInformation200ResponseIngredientsInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:description, :struct, RecipesBot.SpoonacularClient.Model.AnyType, options)
    |> deserialize(:safety_level, :struct, RecipesBot.SpoonacularClient.Model.AnyType, options)
  end
end
