# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetConversationSuggests200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :suggests,
    :words
  ]

  @type t :: %__MODULE__{
          :suggests =>
            RecipesBot.SpoonacularClient.Model.GetConversationSuggests200ResponseSuggests.t(),
          :words => [AnyType]
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.GetConversationSuggests200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :suggests,
      :struct,
      RecipesBot.SpoonacularClient.Model.GetConversationSuggests200ResponseSuggests,
      options
    )
    |> deserialize(:words, :list, RecipesBot.SpoonacularClient.Model.AnyType, options)
  end
end
