# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetShoppingList200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :aisles,
    :cost,
    :startDate,
    :endDate
  ]

  @type t :: %__MODULE__{
          :aisles => [
            RecipesBot.SpoonacularClient.Model.GetShoppingList200ResponseAislesInner.t()
          ],
          :cost => float(),
          :startDate => float(),
          :endDate => float()
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.GetShoppingList200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :aisles,
      :list,
      RecipesBot.SpoonacularClient.Model.GetShoppingList200ResponseAislesInner,
      options
    )
  end
end
