# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetRandomRecipes200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :recipes
  ]

  @type t :: %__MODULE__{
          :recipes => [
            RecipesBot.SpoonacularClient.Model.GetRandomRecipes200ResponseRecipesInner.t()
          ]
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.GetRandomRecipes200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :recipes,
      :list,
      RecipesBot.SpoonacularClient.Model.GetRandomRecipes200ResponseRecipesInner,
      options
    )
  end
end
