# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetRecipePriceBreakdownById200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ingredients,
    :totalCost,
    :totalCostPerServing
  ]

  @type t :: %__MODULE__{
          :ingredients => [
            RecipesBot.SpoonacularClient.Model.GetRecipePriceBreakdownById200ResponseIngredientsInner.t()
          ],
          :totalCost => float(),
          :totalCostPerServing => float()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetRecipePriceBreakdownById200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :ingredients,
      :list,
      RecipesBot.SpoonacularClient.Model.GetRecipePriceBreakdownById200ResponseIngredientsInner,
      options
    )
  end
end
