# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :days
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :name => String.t(),
          :days => [
            RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInner.t()
          ]
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :days,
      :list,
      RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInner,
      options
    )
  end
end
