# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :nutritionSummary,
    :nutritionSummaryBreakfast,
    :nutritionSummaryLunch,
    :nutritionSummaryDinner,
    :day,
    :items
  ]

  @type t :: %__MODULE__{
          :nutritionSummary =>
            RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerNutritionSummary.t()
            | nil,
          :nutritionSummaryBreakfast =>
            RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerNutritionSummary.t()
            | nil,
          :nutritionSummaryLunch =>
            RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerNutritionSummary.t()
            | nil,
          :nutritionSummaryDinner =>
            RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerNutritionSummary.t()
            | nil,
          :day => String.t(),
          :items =>
            [
              RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInnerItemsInner.t()
            ]
            | nil
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :nutritionSummary,
      :struct,
      RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerNutritionSummary,
      options
    )
    |> deserialize(
      :nutritionSummaryBreakfast,
      :struct,
      RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerNutritionSummary,
      options
    )
    |> deserialize(
      :nutritionSummaryLunch,
      :struct,
      RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerNutritionSummary,
      options
    )
    |> deserialize(
      :nutritionSummaryDinner,
      :struct,
      RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerNutritionSummary,
      options
    )
    |> deserialize(
      :items,
      :list,
      RecipesBot.SpoonacularClient.Model.GetMealPlanTemplate200ResponseDaysInnerItemsInner,
      options
    )
  end
end
