# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerItemsInnerValue do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :servings,
    :id,
    :title,
    :imageType
  ]

  @type t :: %__MODULE__{
          :servings => float(),
          :id => float(),
          :title => String.t(),
          :imageType => String.t()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GetMealPlanWeek200ResponseDaysInnerItemsInnerValue do
  def decode(value, _options) do
    value
  end
end
