# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :calories,
    :carbs,
    :fat,
    :protein,
    :recipesUsed
  ]

  @type t :: %__MODULE__{
          :calories =>
            RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200ResponseCalories.t(),
          :carbs =>
            RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200ResponseCalories.t(),
          :fat =>
            RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200ResponseCalories.t(),
          :protein =>
            RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200ResponseCalories.t(),
          :recipesUsed => integer()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :calories,
      :struct,
      RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200ResponseCalories,
      options
    )
    |> deserialize(
      :carbs,
      :struct,
      RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200ResponseCalories,
      options
    )
    |> deserialize(
      :fat,
      :struct,
      RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200ResponseCalories,
      options
    )
    |> deserialize(
      :protein,
      :struct,
      RecipesBot.SpoonacularClient.Model.GuessNutritionByDishName200ResponseCalories,
      options
    )
  end
end
