# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCaloriesConfidenceRange95Percent do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :min,
    :max
  ]

  @type t :: %__MODULE__{
          :min => float(),
          :max => float()
        }
end

defimpl Poison.Decoder,
  for:
    RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCaloriesConfidenceRange95Percent do
  def decode(value, _options) do
    value
  end
end
