# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutrition do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :recipesUsed,
    :calories,
    :fat,
    :protein,
    :carbs
  ]

  @type t :: %__MODULE__{
          :recipesUsed => integer(),
          :calories =>
            RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories.t(),
          :fat =>
            RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories.t(),
          :protein =>
            RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories.t(),
          :carbs =>
            RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories.t()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutrition do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :calories,
      :struct,
      RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories,
      options
    )
    |> deserialize(
      :fat,
      :struct,
      RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories,
      options
    )
    |> deserialize(
      :protein,
      :struct,
      RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories,
      options
    )
    |> deserialize(
      :carbs,
      :struct,
      RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories,
      options
    )
  end
end
