# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseRecipesInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :imageType,
    :url
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :title => String.t(),
          :imageType => String.t(),
          :url => String.t()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseRecipesInner do
  def decode(value, _options) do
    value
  end
end
