# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :nutrition,
    :category,
    :recipes
  ]

  @type t :: %__MODULE__{
          :nutrition =>
            RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutrition.t(),
          :category =>
            RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseCategory.t(),
          :recipes => [
            RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseRecipesInner.t()
          ]
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :nutrition,
      :struct,
      RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutrition,
      options
    )
    |> deserialize(
      :category,
      :struct,
      RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseCategory,
      options
    )
    |> deserialize(
      :recipes,
      :list,
      RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseRecipesInner,
      options
    )
  end
end
