# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :value,
    :unit,
    :confidenceRange95Percent,
    :standardDeviation
  ]

  @type t :: %__MODULE__{
          :value => float(),
          :unit => String.t(),
          :confidenceRange95Percent =>
            RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCaloriesConfidenceRange95Percent.t(),
          :standardDeviation => float()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCalories do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :confidenceRange95Percent,
      :struct,
      RecipesBot.SpoonacularClient.Model.ImageAnalysisByUrl200ResponseNutritionCaloriesConfidenceRange95Percent,
      options
    )
  end
end
