# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.ImageClassificationByUrl200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :category,
    :probability
  ]

  @type t :: %__MODULE__{
          :category => String.t(),
          :probability => float()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.ImageClassificationByUrl200Response do
  def decode(value, _options) do
    value
  end
end
