# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.MapIngredientsToGroceryProducts200ResponseInnerProductsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :upc
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :title => String.t(),
          :upc => String.t()
        }
end

defimpl Poison.Decoder,
  for:
    RecipesBot.SpoonacularClient.Model.MapIngredientsToGroceryProducts200ResponseInnerProductsInner do
  def decode(value, _options) do
    value
  end
end
