# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.MapIngredientsToGroceryProducts200ResponseInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :original,
    :originalName,
    :ingredientImage,
    :meta,
    :products
  ]

  @type t :: %__MODULE__{
          :original => String.t(),
          :originalName => String.t(),
          :ingredientImage => String.t(),
          :meta => [String.t()],
          :products => [
            RecipesBot.SpoonacularClient.Model.MapIngredientsToGroceryProducts200ResponseInnerProductsInner.t()
          ]
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.MapIngredientsToGroceryProducts200ResponseInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :products,
      :list,
      RecipesBot.SpoonacularClient.Model.MapIngredientsToGroceryProducts200ResponseInnerProductsInner,
      options
    )
  end
end
