# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.MapIngredientsToGroceryProductsRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ingredients,
    :servings
  ]

  @type t :: %__MODULE__{
          :ingredients => [String.t()],
          :servings => float()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.MapIngredientsToGroceryProductsRequest do
  def decode(value, _options) do
    value
  end
end
