# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.ParseIngredients200ResponseInnerNutritionPropertiesInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :amount,
    :unit
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :amount => float(),
          :unit => String.t()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.ParseIngredients200ResponseInnerNutritionPropertiesInner do
  def decode(value, _options) do
    value
  end
end
