# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHours do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :operational,
    :delivery,
    :pickup,
    :dine_in
  ]

  @type t :: %__MODULE__{
          :operational =>
            RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational.t()
            | nil,
          :delivery =>
            RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational.t()
            | nil,
          :pickup =>
            RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational.t()
            | nil,
          :dine_in =>
            RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational.t()
            | nil
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHours do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :operational,
      :struct,
      RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational,
      options
    )
    |> deserialize(
      :delivery,
      :struct,
      RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational,
      options
    )
    |> deserialize(
      :pickup,
      :struct,
      RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational,
      options
    )
    |> deserialize(
      :dine_in,
      :struct,
      RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational,
      options
    )
  end
end
