# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.SearchMenuItems200ResponseMenuItemsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :restaurantChain,
    :image,
    :imageType,
    :servings
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :title => String.t(),
          :restaurantChain => String.t(),
          :image => String.t(),
          :imageType => String.t(),
          :servings =>
            RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200ResponseServings.t()
            | nil
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.SearchMenuItems200ResponseMenuItemsInner do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :servings,
      :struct,
      RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200ResponseServings,
      options
    )
  end
end
