# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.SearchCustomFoods200ResponseCustomFoodsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :servings,
    :imageUrl,
    :price
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :title => String.t(),
          :servings => float(),
          :imageUrl => String.t(),
          :price => float()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.SearchCustomFoods200ResponseCustomFoodsInner do
  def decode(value, _options) do
    value
  end
end
