# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.SearchFoodVideos200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :videos,
    :totalResults
  ]

  @type t :: %__MODULE__{
          :videos => [
            RecipesBot.SpoonacularClient.Model.SearchFoodVideos200ResponseVideosInner.t()
          ],
          :totalResults => integer()
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.SearchFoodVideos200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :videos,
      :list,
      RecipesBot.SpoonacularClient.Model.SearchFoodVideos200ResponseVideosInner,
      options
    )
  end
end
