# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.SearchRestaurants200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :restaurants
  ]

  @type t :: %__MODULE__{
          :restaurants =>
            [RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInner.t()]
            | nil
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.SearchRestaurants200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :restaurants,
      :list,
      RecipesBot.SpoonacularClient.Model.SearchRestaurants200ResponseRestaurantsInner,
      options
    )
  end
end
