# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :title,
    :badges,
    :importantBadges,
    :breadcrumbs,
    :generatedText,
    :imageType,
    :ingredientCount,
    :ingredientList,
    :ingredients,
    :likes,
    :nutrition,
    :price,
    :servings,
    :spoonacularScore
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :title => String.t(),
          :badges => [String.t()],
          :importantBadges => [String.t()],
          :breadcrumbs => [String.t()],
          :generatedText => String.t(),
          :imageType => String.t(),
          :ingredientCount => integer() | nil,
          :ingredientList => String.t(),
          :ingredients => [
            RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200ResponseIngredientsInner.t()
          ],
          :likes => float(),
          :nutrition =>
            RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200ResponseNutrition.t(),
          :price => float(),
          :servings =>
            RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200ResponseServings.t(),
          :spoonacularScore => float()
        }
end

defimpl Poison.Decoder,
  for: RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :ingredients,
      :list,
      RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200ResponseIngredientsInner,
      options
    )
    |> deserialize(
      :nutrition,
      :struct,
      RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200ResponseNutrition,
      options
    )
    |> deserialize(
      :servings,
      :struct,
      RecipesBot.SpoonacularClient.Model.SearchGroceryProductsByUpc200ResponseServings,
      options
    )
  end
end
