# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RecipesBot.SpoonacularClient.Model.TalkToChatbot200Response do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :answerText,
    :media
  ]

  @type t :: %__MODULE__{
          :answerText => String.t(),
          :media => [AnyType]
        }
end

defimpl Poison.Decoder, for: RecipesBot.SpoonacularClient.Model.TalkToChatbot200Response do
  import RecipesBot.SpoonacularClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:media, :list, RecipesBot.SpoonacularClient.Model.AnyType, options)
  end
end
